# Generated by Django 6.0.6 on 2026-07-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_track_iswc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('iswc', models.CharField(blank=True, help_text='International Standard Musical Work Code (T-xxx.xxx.xxx-x).', max_length=15, null=True)),
                ('registration_status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to register'), ('submitted', 'Submitted'), ('registered', 'Registered')], default='draft', max_length=16)),
                ('target_pro', models.CharField(blank=True, choices=[('ascap', 'ASCAP'), ('bmi', 'BMI'), ('sesac', 'SESAC'), ('socan', 'SOCAN'), ('other', 'Other'), ('', 'Not set')], default='', help_text='Primary PRO/society for registration intent.', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musical_works', to='catalog.label')),
                ('tracks', models.ManyToManyField(blank=True, help_text='Sound recordings that embody this work.', related_name='musical_works', to='catalog.track')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='WorkShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('writer', 'Writer'), ('composer', 'Composer'), ('publisher', 'Publisher'), ('admin', 'Admin publisher')], default='writer', max_length=16)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ipi_cae', models.CharField(blank=True, help_text='CAE/IPI name number when known.', max_length=11)),
                ('pro_affiliation', models.CharField(blank=True, choices=[('ascap', 'ASCAP'), ('bmi', 'BMI'), ('sesac', 'SESAC'), ('socan', 'SOCAN'), ('other', 'Other'), ('', 'Not set')], default='', max_length=16)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_shares', to='catalog.artist')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='publishing.musicalwork')),
            ],
            options={
                'ordering': ('-percentage', 'contributor_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='musicalwork',
            constraint=models.UniqueConstraint(condition=models.Q(('iswc__isnull', False), models.Q(('iswc', ''), _negated=True)), fields=('label', 'iswc'), name='unique_iswc_per_label_when_set'),
        ),
    ]
