# Generated by Django 6.0.6 on 2026-07-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to register'), ('submitted', 'Submitted'), ('registered', 'Registered')], max_length=16)),
                ('pro_society', models.CharField(blank=True, choices=[('ascap', 'ASCAP'), ('bmi', 'BMI'), ('sesac', 'SESAC'), ('socan', 'SOCAN'), ('other', 'Other'), ('', 'Not set')], default='', max_length=16)),
                ('reference', models.CharField(blank=True, help_text='Society confirmation / work ID when available.', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('occurred_on', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_events_created', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_events', to='publishing.musicalwork')),
            ],
            options={
                'ordering': ('-occurred_on', '-created_at'),
            },
        ),
    ]
