# Generated by Django 6.0.6 on 2026-07-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_sheet', to='catalog.track')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SplitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('artist', 'Artist'), ('producer', 'Producer'), ('featured', 'Featured Artist'), ('writer', 'Writer'), ('label', 'Label'), ('other', 'Other')], default='artist', max_length=16)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('artist', models.ForeignKey(blank=True, help_text='Optional link to a roster artist for payouts and portal access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_entries', to='catalog.artist')),
                ('split_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='splits.splitsheet')),
            ],
            options={
                'ordering': ('-percentage', 'participant_name'),
            },
        ),
    ]
