# Generated by Django 6.0.6 on 2026-07-18 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_track_iswc'),
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Project or brief name (e.g. Netflix S2E4, Brand campaign).', max_length=512)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pitched', 'Pitched'), ('shortlisted', 'Shortlisted'), ('cleared', 'Cleared'), ('licensed', 'Licensed'), ('passed', 'Passed'), ('on_hold', 'On hold')], default='inquiry', max_length=16)),
                ('media_type', models.CharField(choices=[('film', 'Film'), ('tv', 'TV'), ('ad', 'Advertising'), ('trailer', 'Trailer'), ('game', 'Game'), ('social', 'Social / digital'), ('other', 'Other')], default='other', max_length=16)),
                ('client_name', models.CharField(blank=True, help_text='Studio, brand, agency, or production company.', max_length=255)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('territory', models.CharField(blank=True, help_text='e.g. Worldwide, US/CA, EU.', max_length=255)),
                ('exclusivity', models.CharField(blank=True, help_text='Exclusivity terms, if any.', max_length=255)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('term_notes', models.TextField(blank=True, help_text='Use type, term length, revision rights, or other deal terms.')),
                ('pitched_at', models.DateField(blank=True, null=True)),
                ('licensed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_opportunities', to='catalog.artist')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sync_opportunities', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(blank=True, help_text='Optional linked sync contract when the deal closes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_opportunities', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_opportunities_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_opportunities', to='catalog.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_opportunities', to='catalog.release')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_opportunities', to='catalog.track')),
            ],
            options={
                'verbose_name_plural': 'sync opportunities',
                'ordering': ('-updated_at', 'title'),
            },
        ),
    ]
