# Generated by Django 6.0.6 on 2026-07-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('statement_uploaded', 'Statement uploaded'), ('statement_reprocessed', 'Statement reprocessed'), ('statement_processed', 'Statement processed'), ('statement_failed', 'Statement parse failed'), ('run_created', 'Royalty run created'), ('run_consolidated', 'Royalty run consolidated'), ('run_consolidation_failed', 'Run consolidation failed'), ('payout_batch_issued', 'Payout batch issued'), ('payout_marked_paid', 'Payout marked paid'), ('split_sheet_finalized', 'Split sheet finalized')], max_length=32)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.PositiveIntegerField()),
                ('summary', models.CharField(max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system/Celery actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='catalog.label')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['label', '-created_at'], name='audit_audit_label_i_8b9205_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx')],
            },
        ),
    ]
