# Generated by Django 6.0.6 on 2026-07-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_track_iswc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DspDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dsp', models.CharField(choices=[('spotify', 'Spotify'), ('apple', 'Apple Music'), ('amazon', 'Amazon Music'), ('youtube', 'YouTube Music'), ('tidal', 'Tidal'), ('deezer', 'Deezer'), ('other', 'Other')], default='spotify', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('submitted', 'Submitted'), ('live', 'Live'), ('taken_down', 'Taken down'), ('failed', 'Failed')], default='planned', max_length=16)),
                ('distributor', models.CharField(blank=True, help_text='Distributor used for this delivery (DistroKid, FUGA, etc.).', max_length=128)),
                ('target_live_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('live_at', models.DateField(blank=True, null=True)),
                ('store_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsp_deliveries_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsp_deliveries', to='catalog.label')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsp_deliveries', to='catalog.release')),
            ],
            options={
                'verbose_name_plural': 'DSP deliveries',
                'ordering': ('target_live_date', 'dsp'),
                'constraints': [models.UniqueConstraint(fields=('release', 'dsp'), name='unique_dsp_per_release')],
            },
        ),
    ]
