# Generated by Django 6.x — A&R pipeline prospects

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_track_iswc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("researching", "Researching"),
                            ("contacting", "Contacting"),
                            ("meeting", "Meeting"),
                            ("negotiating", "Negotiating"),
                            ("signed", "Signed"),
                            ("passed", "Passed"),
                            ("on_hold", "On hold"),
                        ],
                        default="lead",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("hot", "Hot"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                ("genre", models.CharField(blank=True, max_length=128)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=64)),
                ("spotify_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "other_links",
                    models.TextField(
                        blank=True,
                        help_text="Additional discovery links (SoundCloud, TikTok, press, etc.).",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="How this prospect was discovered (demo, referral, showcase, etc.).",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_prospects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prospects",
                        to="catalog.label",
                    ),
                ),
                (
                    "signed_artist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Roster artist created when this prospect signs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prospect_origin",
                        to="catalog.artist",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "name"),
            },
        ),
    ]
