# Generated by Django 6.0.6 on 2026-07-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_track_iswc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('advance', 'Advance'), ('recording', 'Recording'), ('marketing', 'Marketing'), ('video', 'Video'), ('touring', 'Touring'), ('legal', 'Legal'), ('other', 'Other')], default='other', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='catalog.artist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='catalog.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='catalog.release')),
            ],
            options={
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LabelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('advance', 'Advance'), ('recording', 'Recording'), ('marketing', 'Marketing'), ('video', 'Video'), ('touring', 'Touring'), ('legal', 'Legal'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('incurred_on', models.DateField()),
                ('is_recoupable', models.BooleanField(default=True, help_text="If true, counts toward the artist's unrecouped balance.")),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='catalog.artist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='catalog.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='catalog.release')),
            ],
            options={
                'ordering': ('-incurred_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RecoupmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('charge', 'Charge (unrecouped)'), ('credit', 'Credit (recouped)'), ('adjustment', 'Adjustment')], default='charge', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; entry_type determines debit/credit.', max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('effective_on', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoupment_entries', to='catalog.artist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoupment_entries_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoupment_entries', to='erp.labelexpense')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoupment_entries', to='catalog.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recoupment_entries', to='catalog.release')),
            ],
            options={
                'verbose_name_plural': 'recoupment entries',
                'ordering': ('-effective_on', '-created_at'),
            },
        ),
    ]
