# Generated by Django 6.0.6 on 2026-07-10 14:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.CharField(choices=[('distrokid', 'DistroKid'), ('tunecore', 'TuneCore'), ('cd_baby', 'CD Baby'), ('symphonic', 'Symphonic'), ('onerpm', 'ONErpm'), ('routenote', 'RouteNote'), ('toolost', 'TooLost'), ('fuga', 'FUGA'), ('vydia', 'Vydia'), ('the_orchard', 'The Orchard'), ('other', 'Other')], max_length=32)),
                ('filename', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='royalty_statements/%Y/%m/')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('error_message', models.TextField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_statements', to='catalog.label')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoyaltyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_runs', to='catalog.label')),
                ('statements', models.ManyToManyField(blank=True, related_name='runs', to='royalties.royaltystatement')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
