# Generated by Django 6.0.6 on 2026-07-17 03:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('royalties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_period', models.DateField(blank=True, help_text="Reporting period this row's activity occurred in.", null=True)),
                ('store', models.CharField(blank=True, help_text='DSP/platform, e.g. Spotify.', max_length=128)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('artist_name', models.CharField(blank=True, help_text='Artist name as reported by the distributor.', max_length=255)),
                ('track_title', models.CharField(blank=True, help_text='Track title as reported by the distributor.', max_length=512)),
                ('isrc', models.CharField(blank=True, max_length=12)),
                ('upc', models.CharField(blank=True, max_length=13)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Units/streams for this row.')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Original row exactly as read from the statement file.')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='royalties.royaltystatement')),
                ('track', models.ForeignKey(blank=True, help_text="Matched by ISRC within the statement's label catalog, when possible.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_line_items', to='catalog.track')),
            ],
            options={
                'ordering': ('-sale_period', 'id'),
            },
        ),
    ]
