# Generated by Django 6.0.6 on 2026-07-17 15:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('royalties', '0002_royaltylineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltyrun',
            name='consolidation_error',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RoyaltyRunPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isrc', models.CharField(blank=True, max_length=12)),
                ('track_title', models.CharField(blank=True, max_length=512)),
                ('participant_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=16)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('track_gross', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('unallocated_reason', models.CharField(blank=True, help_text='Set when earnings could not be split (missing or draft split sheet).', max_length=64)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_payouts', to='catalog.artist')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='royalties.royaltyrun')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_payouts', to='catalog.track')),
            ],
            options={
                'ordering': ('-amount', 'participant_name'),
            },
        ),
    ]
