# Generated by Django 6.0.6 on 2026-07-18 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_track_iswc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('campaign_type', models.CharField(choices=[('release', 'Release campaign'), ('playlist', 'Playlist pitch'), ('press', 'Press / PR'), ('social', 'Social'), ('ads', 'Paid ads'), ('other', 'Other')], default='release', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('smart_link_url', models.URLField(blank=True, help_text='External smart link / landing page (Linkfire, Feature.fm, etc.).')),
                ('channels', models.TextField(blank=True, help_text='Channels in play (Spotify, Instagram, press list, playlist targets…).')),
                ('goals', models.TextField(blank=True, help_text='Campaign goals (streams, playlist adds, press hits, etc.).')),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='catalog.artist')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketing_campaigns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='catalog.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='catalog.release')),
            ],
            options={
                'ordering': ('-updated_at', 'title'),
            },
        ),
    ]
