# Generated by Django 6.0.6 on 2026-07-17 15:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('royalties', '0003_royaltyrun_consolidation_error_royaltyrunpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Ready to pay'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('closed', 'Closed')], default='ready', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to='catalog.label')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batch', to='royalties.royaltyrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank transfer ID, check number, or other payment trace reference.', max_length=128)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='catalog.artist')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payments.payoutbatch')),
            ],
            options={
                'ordering': ('-amount', 'participant_name'),
                'constraints': [models.UniqueConstraint(fields=('batch', 'participant_name', 'artist'), name='unique_payout_per_participant_in_batch')],
            },
        ),
    ]
