# Generated by Django 6.0.6 on 2026-07-18 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_track_iswc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('master', 'Master audio'), ('stem', 'Stem'), ('artwork', 'Artwork'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('version_label', models.CharField(blank=True, help_text='e.g. Mastered v3, Cover 3000px', max_length=128)),
                ('file', models.FileField(upload_to='assets/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_assets', to='catalog.artist')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='catalog.label')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_assets', to='catalog.release')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_assets', to='catalog.track')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_assets_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', 'title'),
            },
        ),
    ]
